// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sonradan-gurmeler/Canli.tsx": () => import("../components/mockups/sonradan-gurmeler/Canli.tsx"),
  "./components/mockups/sonradan-gurmeler/Koyu.tsx": () => import("../components/mockups/sonradan-gurmeler/Koyu.tsx"),
  "./components/mockups/sonradan-gurmeler/Sicak.tsx": () => import("../components/mockups/sonradan-gurmeler/Sicak.tsx")
};
